### ISSUE TITLE
ERROR: Failed to automatically obtain modules from user build files

### ISSUE THREAD

**Issue by djzager** [konveyor/tackle-test-generator-cli#310] opened 2022-10-10 20:52 UTC
**Describe the bug**

Using the [quick start guide](https://github.com/konveyor/tackle-test-generator-cli/blob/main/doc/unit/quick_start_guide.md) and the latest image `ghcr.io/konveyor/tackle-test-generator-cli:latest`, `tkltest-unit` seems unable to obtain the modules from the provided "pom.xml" file.

My environment can be recreated with .

**Attachments**

`tkltest_config.toml`:

```
[general]
app_name = "onlinebookstore"
app_classpath_file = ""
monolith_app_path = []
java_jdk_home = ""
test_directory = ""
reports_path = ""
verbose = false
offline_instrumentation = false
build_type = "maven"
max_memory_for_coverage = 4096

[generate]
no_diff_assertions = false
target_class_list = []
excluded_class_list = []
time_limit = 10
app_build_files = ["pom.xml"]
app_build_settings_files = []
bad_path = false
app_build_ant_target = ""

[execute]
app_packages = []
no_create_build_file = false
code_coverage = false
test_class = ""
combine_modules_coverage_reports = false

[dev_tests]
build_targets = [ "test",]
coverage_exec_file = ""
compare_code_coverage = false
use_for_augmentation = false
coverage_threshold = 100

[config.init]

[config.list]

[generate.ctd_amplified]
base_test_generator = "combined"
no_augment_coverage = false
no_ctd_coverage = false
interaction_level = 1
num_seq_executions = 10
reuse_base_tests = false

[generate.evosuite]
criterion = [ "BRANCH",]

[generate.randoop]
```

Shell output:

```
root@12987e8e58c8:/app/tackle-test-cli# tkltest-unit --verbose generate ctd-amplified
[tkltest|20:40:05.120] Loading config file tkltest_config.toml
[tkltest|20:40:29.331] ERROR: Failed to automatically obtain modules from user build files
```

`tkltest_unit.log` is empty.

**Environment information**

`podman run -it --rm --entrypoint bash -v $PWD:/app/tackle-test-cli ghcr.io/konveyor/tackle-test-generator-cli:latest` where `PWD` is the directory where the application under test is located (ie. `/home/dzager/code/onlinebookstore`).

 - CLI version `2.4.0`
 - OS: Linux (container using `podman`)

**Comment by rachelt44** [comment] 2022-10-11 08:38
Here's the link to the app: https://github.com/shashirajraja/onlinebookstore/

**Comment by haim-kermany** [comment] 2022-10-11 13:59
Hi
can you please make sure that .class files was generated under /target
if not, can you please 'mvn compile', and retry tkltest-unit?
tnx

**Comment by jmontleon** [comment] 2022-10-11 15:02
I am to the point of seeing: https://github.com/konveyor/tackle-test-generator-cli/issues/68 on both onlinebookstore and tackle-pathfinder. Unfortunately there is no explanation of how it was resolved, so digging into that as well.

**Comment by rachelt44** [comment] 2022-10-11 15:05
@jmontleon are you getting the `Failed to load class org.slf4j.impl.StaticLoggerBinder` warning or the `NoClassDefFoundError`? the title of #68 is a bit misleading because the actual error was the latter. The logger warning is just a warning we can ignore.

**Comment by jmontleon** [comment] 2022-10-11 15:08
This is what I see at the end of each run:

```
[INFO] ------------------------------------------------------------------------
[tkltest|15:01:16.030] Generating tests for app tackle-pathfinder using config file tkltest_config.toml.
[tkltest|15:01:16.039] Computing coverage goals using CTD
* CTD interaction level: 1
[tkltest|15:01:16.793] ERROR: Computing CTD coverage goals failed: Command '"/usr/lib/jvm/java-11-openjdk/bin/java" -Xmx2048m -cp /opt/tackle-test-generator-cli/tkltest-lib/tackle-test-generator-unit-main-SNAPSHOT.jar:/opt/tackle-test-generator-cli/tkltest-lib/acts_3.2.jar:/opt/tackle-test-generator-cli/tkltest-lib/commons-cli-1.4.jar:/opt/tackle-test-generator-cli/tkltest-lib/soot-4.1.0.jar:/opt/tackle-test-generator-cli/tkltest-lib/axml-2.0.0.jar:/opt/tackle-test-generator-cli/tkltest-lib/slf4j-api-1.7.5.jar:/opt/tackle-test-generator-cli/tkltest-lib/guava-29.0-jre.jar:/opt/tackle-test-generator-cli/tkltest-lib/failureaccess-1.0.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/asm-7.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/asm-analysis-7.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/asm-commons-7.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/asm-tree-7.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/asm-utils-7.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/heros-1.2.0.jar:/opt/tackle-test-generator-cli/tkltest-lib/httpcore-4.4.6.jar:/opt/tackle-test-generator-cli/tkltest-lib/httpclient-4.5.13.jar:/opt/tackle-test-generator-cli/tkltest-lib/jackson-databind-2.12.6.1.jar:/opt/tackle-test-generator-cli/tkltest-lib/jackson-core-2.12.6.jar:/opt/tackle-test-generator-cli/tkltest-lib/jackson-annotations-2.12.6.jar org.konveyor.tackle.testgen.model.CTDTestPlanGenerator  -app tackle-pathfinder -pt /home/jason/Documents/src/github.com/konveyor/tackle-pathfinder/src -clpt /home/jason/Documents/src/github.com/konveyor/tackle-pathfinder/tkltest-output-unit-tackle-pathfinder/tackle-pathfinder_build_classpath.txt -ic 1' returned non-zero exit status 1.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	at soot.SootResolver.initializeProgram(SootResolver.java:91)
	at soot.SootResolver.getProgram(SootResolver.java:386)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:62)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:179)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1067)
	at soot.Scene.loadClassAndSupport(Scene.java:1052)
	at soot.Scene.loadNecessaryClasses(Scene.java:1859)
	at org.konveyor.tackle.testgen.util.Utils.initSootClasses(Utils.java:183)
	at org.konveyor.tackle.testgen.model.RapidTypeAnalysis.performAnalysis(RapidTypeAnalysis.java:87)
	at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.<init>(CTDTestPlanGenerator.java:147)
	at org.konveyor.tackle.testgen.model.CTDTestPlanGenerator.main(CTDTestPlanGenerator.java:1154)

```

**Comment by rachelt44** [comment] 2022-10-11 15:23
@jmontleon so the problem is the java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:336)
	
	Did you verify that the class files indeed exist under the target folder? we assume the application was compiled prior to the invocation of TackleTest. I guess this is an additional step we need to add to the integration, given that class files and other build output artifacts are typically not stored on github

**Comment by jmontleon** [comment] 2022-10-11 15:26
They seem to exist, yes:
```
$ find target/ -type f -name *class 
target/classes/io/tackle/pathfinder/controllers/TranslatorResource.class
target/classes/io/tackle/pathfinder/controllers/QuestionnairesResource.class
target/classes/io/tackle/pathfinder/controllers/AssessmentsResource.class
target/classes/io/tackle/pathfinder/services/TranslatorSvc.class
target/classes/io/tackle/pathfinder/services/AssessmentCreateCommand$AssessmentCreateCommandBuilder.class
target/classes/io/tackle/pathfinder/services/AssessmentCreateCommand.class
target/classes/io/tackle/pathfinder/services/QuestionnaireSvc.class
target/classes/io/tackle/pathfinder/services/AssessmentSvc$AssessmentRiskDto.class
target/classes/io/tackle/pathfinder/services/AssessmentSvc.class
target/classes/io/tackle/pathfinder/services/BulkCreateSvc.class
target/classes/io/tackle/pathfinder/services/BulkOperation$BulkOperationBuilder.class
target/classes/io/tackle/pathfinder/services/BulkOperation.class
target/classes/io/tackle/pathfinder/dto/translator/TranslateDBDto$TranslateDBDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/translator/TranslateDBDto$TranslateDBDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/translator/TranslateDBDto.class
target/classes/io/tackle/pathfinder/dto/BasicDto$BasicDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/BasicDto.class
target/classes/io/tackle/pathfinder/dto/AdoptionCandidateDto$AdoptionCandidateDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AdoptionCandidateDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentStatus.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionnaireDto$AssessmentQuestionnaireDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionnaireDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentCategoryDto$AssessmentCategoryDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentCategoryDto$AssessmentCategoryDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentCategoryDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionDto$AssessmentQuestionDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionDto$AssessmentQuestionDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionOptionDto$AssessmentQuestionOptionDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionOptionDto$AssessmentQuestionOptionDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentQuestionOptionDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentBulkPostDto$AssessmentBulkPostDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentBulkPostDto.class
target/classes/io/tackle/pathfinder/dto/ApplicationDto$ApplicationDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/ApplicationDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderBulkDto$AssessmentHeaderBulkDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderBulkDto$AssessmentHeaderBulkDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderBulkDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderDto$AssessmentHeaderDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderDto$AssessmentHeaderDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentHeaderDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentDto$AssessmentDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentDto$AssessmentDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/AssessmentDto.class
target/classes/io/tackle/pathfinder/dto/RiskLineDto$RiskLineDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/RiskLineDto.class
target/classes/io/tackle/pathfinder/dto/AssessmentBulkDto$AssessmentBulkDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/AssessmentBulkDto.class
target/classes/io/tackle/pathfinder/dto/questionnaire/QuestionnaireHeaderDto$QuestionnaireHeaderDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/questionnaire/QuestionnaireHeaderDto$QuestionnaireHeaderDtoBuilderImpl.class
target/classes/io/tackle/pathfinder/dto/questionnaire/QuestionnaireHeaderDto.class
target/classes/io/tackle/pathfinder/dto/LandscapeDto.class
target/classes/io/tackle/pathfinder/dto/ApplicationBulkDto$ApplicationBulkDtoBuilder.class
target/classes/io/tackle/pathfinder/dto/ApplicationBulkDto.class
target/classes/io/tackle/pathfinder/model/i18n/TranslatedText$TranslatedTextBuilder.class
target/classes/io/tackle/pathfinder/model/i18n/TranslatedText.class
target/classes/io/tackle/pathfinder/model/questionnaire/SingleOption$SingleOptionBuilder.class
target/classes/io/tackle/pathfinder/model/questionnaire/SingleOption.class
target/classes/io/tackle/pathfinder/model/questionnaire/Question$QuestionBuilder.class
target/classes/io/tackle/pathfinder/model/questionnaire/Question.class
target/classes/io/tackle/pathfinder/model/questionnaire/Category$CategoryBuilder.class
target/classes/io/tackle/pathfinder/model/questionnaire/Category.class
target/classes/io/tackle/pathfinder/model/questionnaire/Questionnaire$QuestionnaireBuilder.class
target/classes/io/tackle/pathfinder/model/questionnaire/Questionnaire.class
target/classes/io/tackle/pathfinder/model/Risk.class
target/classes/io/tackle/pathfinder/model/QuestionType.class
target/classes/io/tackle/pathfinder/model/Constants.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentQuestionnaire$AssessmentQuestionnaireBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentQuestionnaire.class
target/classes/io/tackle/pathfinder/model/assessment/Assessment$AssessmentBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/Assessment.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentCategory$AssessmentCategoryBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentCategory.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentQuestion$AssessmentQuestionBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentQuestion.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentSingleOption$AssessmentSingleOptionBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentSingleOption.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentStakeholder$AssessmentStakeholderBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentStakeholder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentStakeholdergroup$AssessmentStakeholdergroupBuilder.class
target/classes/io/tackle/pathfinder/model/assessment/AssessmentStakeholdergroup.class
target/classes/io/tackle/pathfinder/model/bulk/AssessmentBulkApplication$AssessmentBulkApplicationBuilder.class
target/classes/io/tackle/pathfinder/model/bulk/AssessmentBulkApplication.class
target/classes/io/tackle/pathfinder/model/bulk/AssessmentBulk$AssessmentBulkBuilder.class
target/classes/io/tackle/pathfinder/model/bulk/AssessmentBulk.class
target/classes/io/tackle/pathfinder/exception/ValidationExceptionMapper.class
target/classes/io/tackle/pathfinder/exception/BadRequestExceptionMapper.class
target/classes/io/tackle/pathfinder/exception/NotFoundExceptionMapper.class
target/classes/io/tackle/pathfinder/exception/GlobalExceptionMapper.class
target/classes/io/tackle/pathfinder/exception/InvalidFormatExceptionMapper.class
target/classes/io/tackle/pathfinder/mapper/TranslatorMapper.class
target/classes/io/tackle/pathfinder/mapper/AssessmentMapper.class
target/classes/io/tackle/pathfinder/mapper/QuestionnaireMapper.class
target/classes/io/tackle/pathfinder/mapper/QuestionnaireMapperImpl.class
target/classes/io/tackle/pathfinder/mapper/AssessmentMapperImpl.class
target/classes/io/tackle/pathfinder/security/DisabledAuthController.class
```

**Comment by rachelt44** [comment] 2022-10-11 15:31
@jmontleon so what happens if you give `target/classes` as the monolith app path?

**Comment by jmontleon** [comment] 2022-10-11 16:23
That finished after some time:
```
[tkltest|16:17:02.699] Generated tests are integrated into ../pom.xml. New build file is saved as: /home/jason/Documents/src/github.com/konveyor/tackle-pathfinder/tkltest_app_pom.xml.
```

On the next step on the quick start guide I now get:
```
$ podman run --replace --name tkltest-unit --rm -it --entrypoint tkltest-unit -v $HOME/.m2:/root/.m2:z -v $PWD:$PWD:z -v $PWD/target:/target:z -w $PWD tkltest-unit --verbose --test-directory tkltest-output-unit-tackle-pathfinder/tackle-pathfinder-ctd-amplified-tests execute
[tkltest|16:18:20.226] Loading config file tkltest_config.toml
[tkltest|16:18:20.227] ERROR: configuration options validation failed:
	- Missing required options for "execute": ['app_packages']

```

I guess we need to fill something in for:
```
[execute]
app_packages = []
```

in tkltest_config.toml ?

**Comment by jmontleon** [comment] 2022-10-11 16:29
app_packages = ["io.tackle.pathfinder.controllers"] ran tests and worked it looks like. Is it possible/reasonable to use a wildcard here?

FWIW, we're trying to run through the quickstart guide at https://github.com/konveyor/tackle-test-generator-cli/blob/main/doc/unit/quick_start_guide.md

I'll see if I can reproduce the successful results. Thank you for the help so far.

**Comment by rachelt44** [comment] 2022-10-11 17:51
@jmontleon app packages entries should always include a wildcard at the end. E.g., `io.tackle.pathfinder.controllers.*`, but also `io.tackle.*` is possible

**Comment by rachelt44** [comment] 2022-10-11 18:10
Glad to hear! my pleasure

**Comment by haim-kermany** [comment] 2022-10-12 07:32
can you please share the tkltest_config.toml that you have?

**Comment by rachelt44** [comment] 2022-10-12 07:36
@haim-kermany the `tkltest_config.toml` file appears in the first message in this issue

**Comment by rachelt44** [comment] 2022-10-12 07:50
@jmontleon please note that the execute command is not in the scope of the addon, only generate is going to be used by Tackle.

**Comment by jmontleon** [comment] 2022-10-12 14:18
@rachelt44 Understood. That was my understandinf from @djzager as well. It was more for my familiarization. 

@haim-kermany I am trying onlinebookstore now and it is telling me it can't generate any tests after spitting out a very long error (happy to provide it in full)

I'm cloning online bookstore, generating a config, editing just the two values:
```
[general]
app_name = "onlinebookstore"

[generate]
app_build_files = [ "pom.xml" ]
```

After that I get a huge list of errors. I've put them in pastebin here: https://paste.centos.org/view/c2cb49fe

**Comment by rachelt44** [comment] 2022-10-12 16:21
@jmontleon I'm looking into this error. Just verifying that you got this while running with Java 11?

**Comment by jmontleon** [comment] 2022-10-12 17:05
To add, I looked quick, and onlinebookstore, only lists 8+ as a requirement, so if it's something to do with running on 11 in this case we could back down. I have not tried yet though.

**Comment by rachelt44** [comment] 2022-10-13 10:58
@jmontleon there is a difference in behavior between java 8 and 11, but it is failing with both. With java 11, evosuite (one of the open source test generators we are using) is failing to instrument the class files. With java 8 it runs successfully,  but later TackleTest is failing to generate any test sequences from the output of evosuite (I've never seen such a behavior before). I'm opening a separate issue for this specific problem.

**Comment by rachelt44** [comment] 2022-10-13 11:54
@jmontleon after further looking into onlinebookstore code, apparently it is not suitable for automatic unit test generation after all. Its entire code consists of transactions with the database, there is no other logic in the code. Unfortunately when we run automatic unit test generation the DB is not set up, and we do not mock the database automatically, hence any attempt to connect to the DB will fail, and any test generation of such code will fail.

**Comment by jmontleon** [comment] 2022-10-13 13:50
Thank you for the explanation @rachelt44, that all makes sense. I think we're OK to close this for now. We'll look for an alternate project to test with in addition to tackle-pathfinder (also happy to take suggestions).

**Comment by rachelt44** [comment] 2022-10-13 14:34
@jmontleon one of our regression projects is windup-sample (https://github.com/konveyor/tackle-test-generator-cli/tree/main/test/data/windup-sample), which is a multi-module maven project so testing also that aspect. Will this work for you?

**Comment by jmontleon** [comment] 2022-10-13 14:37
Sure, I'll give that a shot. Thank you!

**Closed by jmontleon** 2022-10-13 14:37 UTC
