### ISSUE TITLE
JaCoCo report generation error with instrumented class

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#120] opened 2021-11-22 10:42 UTC
**Describe the bug**

JaCoCo report generation fails when there is an instrumented class generated. The error reported is:

```text
[INFO] --- jacoco-maven-plugin:0.8.7:report (generate-code-coverage-report) @ Jacoco ---
[INFO] Loading execution data file /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests/monolithic/jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.767 s
[INFO] Finished at: 2021-11-22T10:59:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:report (generate-code-coverage-report) on project Jacoco: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing /home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest-output-simple-sample-services/../tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests/target/classes/com/acme/anvil/service/jms/LogEventPublisher.class. Cannot process instrumented class com/acme/anvil/service/jms/LogEventPublisher. Please supply original non-instrumented classes. -> [Help 1]
```

This error is reported with a simple JEE application with EJB, JMS and Servlets. The original source code is available [here](https://github.com/windup/migration-sample-app).

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

- The toml file containing the configuration information used

```text
[general]
    app_name = "simple-sample-services"
    app_classpath_file = "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_classpath.txt"
    monolith_app_path = [
        "/home/rmarting/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/target/classes"
    ]
    java_jdk_home = ""
    test_directory = ""
    reports_path = ""
    verbose = true

[generate]
    jee_support = true
    no_diff_assertions = false
    partitions_file = ""
    target_class_list = []
    excluded_class_list = []
    time_limit = 10
    app_build_config_file = "pom.xml"
    app_build_settings_file = ""

[generate.ctd_amplified]
    base_test_generator = "combined"
    augment_coverage = false # true fails
    no_ctd_coverage = false
    interaction_level = 1
    num_seq_executions = 10
    refactored_app_path_prefix = ""
    refactored_app_path_suffix = []
    reuse_base_tests = false

[generate.evosuite]
    criterion = [ "BRANCH",]

[generate.randoop]
    no_error_revealing_tests = false

[execute]
    app_packages = [ "com.acme.anvil.*" ]
    build_type = "maven"
    create_build_file = false
    code_coverage = true
    online_instrumentation = false
    test_class = ""
```

- Command to generate tests:

```shell
tkltest \
    --config-file ~/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml \
    generate \
    ctd-amplified
```

- Command to execute tests:

```shell
tkltest \
    --config-file ~/Workspaces/ws-konveyor/sample-apps/migration-sample-app/simple-sample-services/tkltest_config.toml \
    --test-directory tkltest-output-simple-sample-services/simple-sample-services-ctd-amplified-tests \
    execute
```

**Environment information**

 - CLI version 1.0.0 generated from main branch
 - OS:
```shell
❯ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
❯ uname -a
Linux redhat 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots**

**Additional context**

The content of the `tkltest_classpath.txt` file is:

```text
$HOME/.m2/repository/org/jboss/windup/test/apps/weblogic/simple-sample-weblogic-services/1.0.0-SNAPSHOT/simple-sample-weblogic-services-1.0.0-SNAPSHOT.jar
$HOME/.m2/repository/org/jboss/ejb3/jboss-ejb3-ext-api/2.1.0/jboss-ejb3-ext-api-2.1.0.jar
$HOME/.m2/repository/javax/javaee-api/7.0/javaee-api-7.0.jar
$HOME/.m2/repository/com/sun/mail/javax.mail/1.5.0/javax.mail-1.5.0.jar
$HOME/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
$HOME/.m2/repository/org/jboss/windup/test/apps/weblogic/proprietary-stub/1.0.0-SNAPSHOT/proprietary-stub-1.0.0-SNAPSHOT.jar
$HOME/.m2/repository/javaee/javaee-api/5/javaee-api-5.jar
$HOME/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
$HOME/.m2/repository/org/jboss/logging/jboss-logging/3.1.4.GA/jboss-logging-3.1.4.GA.jar
$HOME/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
$HOME/.m2/repository/javax/ejb/ejb-api/3.0/ejb-api-3.0.jar
$HOME/.m2/repository/org/jboss/ejb3/jboss-ejb3-ext-api/2.1.0/jboss-ejb3-ext-api-2.1.0.jar
$HOME/.m2/repository/javaee/javaee-api/5/javaee-api-5.jar
```

**Comment by rachelt44** [comment] 2021-11-22 11:50
@rmarting this issue is related to another issue - currently our generated maven build file doesn't support offline instrumentation, which is the default instrumentation (I'm changing default to be online). Once we fix issue #109 we'll try this again to verify it works. 

https://github.com/konveyor/tackle-test-generator-cli/issues/109

**Comment by rmarting** [comment] 2021-11-22 12:00
However I found the same issue with the following property enabled:

```text
[execute]
    online_instrumentation = true
```

Is that property for other purpose?

**Comment by rachelt44** [comment] 2021-11-22 12:05
@rmarting this property is for the same purpose. So if it doesn't work with online instrumentation then the root cause is different. We'll investigate and let you know. Thanks for checking it!

**Comment by rachelt44** [comment] 2021-12-22 10:24
@rmarting I believe I have solved this issue, but to be absolutely sure before I create a PR I want to run the execute command on the set of test cases you generated (there is some randomness in generation, so the tests I generated may differ from yours). Can you please send me the content of `simple-sample-services-ctd-amplified-tests`? 

Also note that you will have to set the config option `execute.create_build_file` to `false` because the `pom.xml` for the tests needs to be re-generated, and that we changed and moved the config option `execute.online_instrumentation` to `general.offline_instrumentation` (so default now changed to perform online instrumentation, but I'm checking it with both offline and online)

**Comment by rmarting** [comment] 2021-12-23 07:06
@rachelt44 Uploaded the content of tha folder.

Some updates:
- I used the latest version of tk-test from the `main` branch
- change the toml file with your comments about some of the properties

[simple-sample-services-ctd-amplified-tests.zip](https://github.com/konveyor/tackle-test-generator-cli/files/7767363/simple-sample-services-ctd-amplified-tests.zip)

HTH

**Comment by rachelt44** [comment] 2021-12-23 11:52
@rmarting Thank you! it works for me both with offline and online instrumentation. Please confirm if it works for you as well so we can close it.

**Comment by rmarting** [comment] 2021-12-23 13:03
Repeated the process using the latest version from `main` branch and now it is working successfully. I added the next changes in my `toml` file:

```
[general]
    # online_instrumentation = false
    offline_instrumentation = false
    build_type = "maven"
[execute]
    build_type = "maven"
    create_build_file = true
```

So we could confirm this issue. Thanks!

**Comment by rachelt44** [comment] 2021-12-23 13:05
@rmarting thank you for your prompt response! note that `build_type` is now needed in `general` section only.

**Closed by rachelt44** 2021-12-23 13:05 UTC
Labels: bug
