### ISSUE TITLE
ERROR: running maven command

### ISSUE THREAD

**Issue by djzager** [konveyor/tackle-test-generator-cli#311] opened 2022-10-10 20:57 UTC
**Describe the bug**

A clear and concise description of what the failure is, including information about
the complete CLI command used (`generate` or `execute` command, with sub-command and options)
and the error message. 

**Attachments**

`tkltest_config.toml`:

```
[general]
app_name = "tackle-pathfinder"
app_classpath_file = ""
monolith_app_path = [""]
java_jdk_home = ""
test_directory = ""
reports_path = ""
verbose = true
offline_instrumentation = false
build_type = "maven"
max_memory_for_coverage = 4096

[generate]
no_diff_assertions = false
target_class_list = []
excluded_class_list = []
time_limit = 10
app_build_files = ["pom.xml"]
app_build_settings_files = []
bad_path = false
app_build_ant_target = ""

[execute]
app_packages = []
no_create_build_file = false
code_coverage = false
test_class = ""
combine_modules_coverage_reports = false

[dev_tests]
build_targets = [ "test",]
coverage_exec_file = ""
compare_code_coverage = false
use_for_augmentation = false
coverage_threshold = 100

[config.init]

[config.list]

[generate.ctd_amplified]
base_test_generator = "combined"
no_augment_coverage = false
no_ctd_coverage = false
interaction_level = 1
num_seq_executions = 10
reuse_base_tests = false

[generate.evosuite]
criterion = [ "BRANCH",]

[generate.randoop]
```

Execution output:

```
root@00ac5e50afe3:/app/tackle-test-cli# tkltest-unit --verbose generate ctd-amplified
[tkltest|20:47:43.704] Loading config file tkltest_config.toml
[tkltest|20:48:13.800] ERROR: running maven command "mvn --quiet -f pom.xml exec:exec -Dexec.executable="echo" -Dexec.args='{ _tkltest_quot_name_tkltest_quot_ : _tkltest_quot_${project.artifactId}_tkltest_quot_, _tkltest_quot_directory_tkltest_quot_ : _tkltest_quot_${basedir}_tkltest_quot_, _tkltest_quot_build_file_tkltest_quot_ : _tkltest_quot_${basedir}/pom.xml_tkltest_quot_, _tkltest_quot_app_path_tkltest_quot_ : _tkltest_quot_${project.build.outputDirectory}_tkltest_quot_, _tkltest_quot_user_build_file_tkltest_quot_ : _tkltest_quot_pom.xml_tkltest_quot_ },' >> /app/tackle-test-cli/tkltest-output-unit-tackle-pathfinder/tackle-pathfinder_modules_properties.json" failed: Command 'mvn --quiet -f pom.xml exec:exec -Dexec.executable="echo" -Dexec.args='{ _tkltest_quot_name_tkltest_quot_ : _tkltest_quot_${project.artifactId}_tkltest_quot_, _tkltest_quot_directory_tkltest_quot_ : _tkltest_quot_${basedir}_tkltest_quot_, _tkltest_quot_build_file_tkltest_quot_ : _tkltest_quot_${basedir}/pom.xml_tkltest_quot_, _tkltest_quot_app_path_tkltest_quot_ : _tkltest_quot_${project.build.outputDirectory}_tkltest_quot_, _tkltest_quot_user_build_file_tkltest_quot_ : _tkltest_quot_pom.xml_tkltest_quot_ },' >> /app/tackle-test-cli/tkltest-output-unit-tackle-pathfinder/tackle-pathfinder_modules_properties.json' returned non-zero exit status 1.
```

`tkltest_unit.log` is empty

**Environment information**

`podman run -it --rm --entrypoint bash -v $PWD:/app/tackle-test-cli ghcr.io/konveyor/tackle-test-generator-cli:latest` where PWD is where [tackle-pathfinder](https://github.com/konveyor/tackle-pathfinder) was cloned

 - CLI version `2.4.0`
 - OS: Linux

**Comment by jmontleon** [comment] 2022-10-11 13:21
For what it's worth at least part of the problem is the java 8 base image. The pathfinder app uses quarkus, and at least with the version it uses it has a minimum requirement of Java 11, 

I was able to see it build using this Dockerfile: https://github.com/jmontleon/tackle2-addon-test-generator/blob/update-dockerfile/Dockerfile

Then I end up in the same situation as #310

**Comment by rachelt44** [comment] 2022-10-11 13:24
@jmontleon TackleTest was tested with Java 8-11 and officially supports these versions, but will probably not work with versions higher than 11 due to some of the open source packages we are using that do not have this support.

**Comment by jmontleon** [comment] 2022-10-11 13:25
Thanks for the heads up @rachelt44. I'll use 11 instead.

**Comment by rachelt44** [comment] 2022-10-13 12:11
@jmontleon can we close this issue for running tackletest on tackle-pathfinder? I understand this is working now.

**Comment by jmontleon** [comment] 2022-10-13 13:51
I think we can close this. If we encounter other new problems we can open a new issue. Thank you for your help!

**Closed by jmontleon** 2022-10-13 13:51 UTC
