### ISSUE TITLE
Upgrade to use newest Java 11 (or newest Java LTS versions)

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#88] opened 2021-10-11 15:02 UTC
**Is your feature request related to a problem? Please describe.**

Java 8 is an older version of Java, still valid as LTS version, but not optimized with the latest features or capabilities of newer versions of Java. Java 11 is still the most extended, also a LTS version, and common in enterprise environments, it makes sense to use this runtime to build the tool.

**Describe the solution you'd like**

Update build files (e.g.: pom.xml) and documentation to use newer versions of Java (at least Java 11) instead of Java 8.

**Additional context**

Use a newest LTS version instead of Java 8 will improve the quality and perception of the tool for the users.

**Comment by sinha108** [comment] 2022-01-03 15:34
Duplicate of https://github.com/konveyor/tackle-test-generator-core/issues/102

**Closed by sinha108** 2022-01-03 15:34 UTC
Labels: enhancement
